<img src="https://raw.githubusercontent.com/paular143/images_notebooks/master/logo-sin-nombre.png" alt="Universidad de Los Andes" style="width: 90px;" align="left" frameborder="300"/>

**UNIVERSIDAD DE LOS ANDES** <br>
**FACULTAD DE ECONOMÍA** <br>
**Taller de Python** <br>
**PROFESOR:** Germán González <br><br>

**Taller 2** <br><br>

Actualmente nos encontramos en medio de una pandemia causada por COVID-19. Dada la coyuntura trabajaremos con las bases de las series de tiempo de la Universidad John Hopkins.

En el <a href='https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series'>link</a> encontrará con cinco bases de datos:
- confirmed_global.csv: tiene el número de casos día a día para todos los países del mundo.
- confirmed_US.csv: tiene el número de casos día a día para todos los counties (el análogo de municipios en EEUU).
- deaths_global.csv: tiene el número de muertos día a día para todos los países del mundo.
- deaths_US.csv: tiene el número de muertos día a día para todos los counties (el análogo de municipios en EEUU).
- recovered_global: tiene el número de recuperados día a día en el mundo

Las preguntas a continuación no tienen que ser respondidas en ningún orden particular, solo debe ser claro sobre cual está respondiendo (comente su código o use las celdas markdown como esta).

El objetivo de este ejercicio es que practiquen la manipulación de bases de datos para responder a preguntas concretas. Es posible que usen funciones que aún no hayamos visto, apoyense en Google, stackoverflow, blogs, Medium, etc... para hacer sus códigos. Si quieren trabajen en parejas o de manera individual, dejando claro en este notebook con quien trabajaron. Diviértanse aprendiendo a programar y solucionar un proyecto más cercano a la realidad.

# Parte A:
1. ¿Cuál es el país con más muertos hasta el momento?
2. ¿Cuál es el país con la tasa de mortalidad más alta?
3. ¿Cuál es el país que ha tenido una tasa de contagio más alta? Esta pregunta tiene muchas formas de resolverse, justifique el método que usó y muestre los resultados.
4. ¿Cuál es el país que se ha recuperado más rápido? Esta pregunta tiene muchas formas de resolverse, justifique el método que usó y muestre los resultados.

In [3]:
import pandas as pd

In [4]:
covid_global=pd.read_csv("csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
covid_global.drop(covid_global.index[[225]],inplace=True)

In [5]:
muertes_global=pd.read_csv("csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
muertes_global.drop(muertes_global.index[[225]],inplace=True)

In [6]:
recuperados_global=pd.read_csv("csse_covid_19_time_series/time_series_covid19_recovered_global.csv")
recuperados_global.drop(recuperados_global.index[[225]],inplace=True)

In [18]:
recuperados_global

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,10/23/21,10/24/21,10/25/21,10/26/21,10/27/21,10/28/21,10/29/21,10/30/21,10/31/21,11/1/21
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,NaN,Vietnam,14.058324,108.277199,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
261,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
262,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
263,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
264,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Parte B
1. Note que las bases que corresponden a los datos globales tienen algunos países desagregados por varias regiones. Lo primero que debe hacer el agrupar para que quede toda la base a nivel de observación de países en su totalidad.
2. Note que hay una base aparte de EEUU. Construya la observación de EEUU de casos confirmados y verifique si es igual a la base a la base de confirmados globales. En caso contrario reemplaze la observación en la base de confirmados globales. 
3. Haga lo mismo que los puntos anteriores pero para los datos de muertos. 
4. Grafique las series de tiempo en un solo gráfico para los países de Sudamérica de casos confirmados. Haga el mismo gráfico para muertos. Haga el mismo gráfico para recuperados
5. Calcule las tasas de crecimiento de contagiados y muertos por país diarias. Calcule la tasa de crecimiento diario de contagiados y la de muertos __promedio__ del mundo y grafique esta serie.
6. Construya su propio _insight_ de esta base de datos que muestre algo interesante sobre la progresión de esta pandemia, encuentre algo que usted no conoce o haya escuchado en los medios de comunicación. Apóyese en su conocimientos técnicos como economista (observe elasticidades, cocientes, estudie rezagos, normalizaciones, etc).